name: Compilar y desplegar

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'BibliotecaAPI/**'
      - 'BibliotecaAPITests/**'
      - '.github/workflows/compilar-y-desplegar.yml'

env:  # variable de ambiente
  VERSION_DOTNET: '9'
  AZURE_APP_SERVICE_NOMBRE: 'BibliotecaAPI20250619075519'
  AZURE_APP_SERVICE_UBICACION_PAQUETE: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      proyecto: BibliotecaAPI/BibliotecaAPI.csproj
    steps:
      - name: Checkout  # Traemos los archivos del repositorio
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: ${{ env.VERSION_DOTNET }}

      - name: Obtener dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore  # Se pone --not-restore ya que se ha hecho el `restore` en el paso anterior

      - name: Realizar pruebas automáticas
        run: dotnet test --no-build  # Como antes se ha hecho el `build` pues ahora `--no-bjuild`

      - name: Publicar el WebAPI
        run: dotnet publish $proyecto -c Release -o miapp -runtime win-x86

      - name: Cargar artefacto
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./miapp
          name: buildAPI

  despliegue:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build  # necesita que se termine el proceso build para iniciar su ejecución
    steps:
      - name: Obtener los artefactos
        uses: actions/download-artifact@v4.3.0
        with:
          name: buildAPI

      - name: Despliegue hacia Azure
        uses: Azure/webapps-deploy@v2.2.12
        with:
          app-name: ${{ env.AZURE_APP_SERVICE_NOMBRE }}
          publish-profile: ${{ secrets.AZURE_PERFIL_PUBLICO }}
          package: ${{ enc.AZURE_APP_SERVICE_UBICACION_PAQUETE }}
          
